name: WordPress Plugin Check

on:
  pull_request:
    paths:
      - 'wp-plugin/**'

jobs:
  plugin-check:
    runs-on: ubuntu-latest
    name: WordPress Plugin Check
    steps:
      - uses: actions/checkout@v4

      - name: WordPress Plugin Check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: './wp-plugin'
